name: Build Mod
on:
  push:
    branches: [ "pr178", "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # Собираем сразу под все три платформы
        target: [cpu, cuda, windows]
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v3

    - name: Build with Gradle
      run: ./gradlew build -PonnxTarget=${{ matrix.target }} --no-daemon --stacktrace

    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: terrain-diffusion-${{ matrix.target }}
        path: "**/build/libs/*.jar"
